name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install mkdocs
        python3 -m pip install mkdocs-material

    - run: mkdocs build --config-file ./mkdocs.yml

    - name: Deploy to GitHub Pages
      uses: docker://peaceiris/gh-pages:v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
